<a href="https://colab.research.google.com/github/A01286211/M1-Act5-SZD/blob/main/M1_Actividad_5_Programaci%C3%B3n_en_Python_Librer%C3%ADas_Numpy_Matplotlib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M1 Act 5 Programación en Python
### Sebastián Zaragoza Díaz A01286211
### Análisis de Ciencia de Datos (Gpo 101)
### Prof. Rasikh Tariq

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Ejercicio 1 - Numpy

 1. Crear un vector “x” con 10 ceros y mostrarlo.

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Modificar el quinto elemento del vector x para que su valor sea 3.

In [4]:
x[4] = 3 # índice del vector comienza en 0
print(x)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


3. Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.

In [5]:
y = np.arange(1,21)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


4. Crear un vector “z” con valores del 1 al 20, de 2 en 2.

In [6]:
z = np.arange(1,20,2)
print(z)

[ 1  3  5  7  9 11 13 15 17 19]


5. Crear una matriz w de 3x2, con valores iniciales en 0.

In [7]:
w = np.zeros([3,2])
print(w)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


6. Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.

In [8]:
w[1,1] = 5 # De nuevo, índice comienza en 0
print(w)

[[0. 0.]
 [0. 5.]
 [0. 0.]]


7. Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.

In [9]:
vec5 = np.random.randint(1,11,5)
print(vec5)

[1 2 9 9 6]


8. Crear el arreglo x1 de la lista [1,2,3]

In [10]:
x1 = np.array([1,2,3])
print(x1)

[1 2 3]


9.  Sumar 10 a cada elemento del vector

In [11]:
x1 = x1 + 10
print(x1)

[11 12 13]


### Ejercicio 2 - Titanic

1. Generar un DataFrame con los datos del archivo.

In [13]:
data = pd.read_csv('/content/titanic-1.csv')

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

2. Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas

In [15]:
dataSize = data.size
print(f'El DataFrame contiene {dataSize} datos')

El DataFrame contiene 10692 datos


In [27]:
dataCol = data.columns
print(f'Los nombres de las columnas del DataFrame son: \n{dataCol}')

Los nombres de las columnas del DataFrame son: 
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [23]:
dataColType = data.dtypes
print(f'Los tipos de datos de las columnas del DataFrame son: \n{dataColType}')

Los tipos de datos de las columnas del DataFrame son: 
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [28]:
TenFirst = data.head(10)
print('Las primeras 10 filas son:\n')
TenFirst

Las primeras 10 filas son:



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [29]:
TenLast = data.tail(10)
print('Las últimas 10 filas son: \n')
TenLast

Las últimas 10 filas son: 



PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

3. Mostrar por pantalla los datos del pasajero con identificador 148.

In [38]:
Id148 = data.loc[data['PassengerId'] == 148]
print('Los datos del Pasajero con Id 148 es: \n')
Id148

Los datos del Pasajero con Id 148 es: 



PassengerId  Survived  Pclass                              Name     Sex  \
147          148         0       3  Ford, Miss. Robina Maggie "Ruby"  female   

     Age  SibSp  Parch      Ticket    Fare Cabin Embarked  
147  9.0      2      2  W./C. 6608  34.375   NaN        S

4. Mostrar por pantalla las filas pares del DataFrame.


In [40]:
EvenRows = data.loc[data.index % 2 == 0]
print('Las filas pares del DataFrame son: \n')
EvenRows

Las filas pares del DataFrame son: 



PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
4              5         0       3   
6              7         0       1   
8              9         1       3   
..           ...       ...     ...   
882          883         0       3   
884          885         0       3   
886          887         0       2   
888          889         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
2        0  STON/O2. 3101282   7.9250   NaN        S  
4        0            373450   8.0500   NaN        S  
6        0             17463  51.8625   E46        S  
8        2            347742  11.1333   NaN        S  
..     ...               ...      ...   ...      ...  
882      0              7552  10.5167   NaN        S  
884      0   SOTON/OQ 392076   7.0500   NaN        S  
886      0            211536  13.0000   NaN        S  
888      2        W./C. 6607  23.4500   NaN        S  
890      0            370376   7.7500   NaN        Q  

[446 rows x 12 columns]

5. Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.

In [49]:
FClass = data.loc[data['Pclass'] == 1]
FOrdered = FClass.sort_values(by = 'Name')
print('Las personas que iban en primera fila, alfabéticamente son: \n')
FOrdered.Name

Las personas que iban en primera fila, alfabéticamente son: 



730                      Allen, Miss. Elisabeth Walton
305                     Allison, Master. Hudson Trevor
297                       Allison, Miss. Helen Loraine
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
460                                Anderson, Mr. Harry
                            ...                       
155                        Williams, Mr. Charles Duane
351             Williams-Lambert, Mr. Fletcher Fellows
55                                   Woolner, Mr. Hugh
555                                 Wright, Mr. George
325                           Young, Miss. Marie Grice
Name: Name, Length: 216, dtype: object

6. Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.

In [51]:
surv = data.loc[data['Survived'] == 1].size
died = data.loc[data['Survived'] == 0].size
total = dataSize

survPerc = (surv/total)*100
diedPerc = (died/total)*100

print(f'Porcentaje de personas que sobrevivieron: {round(survPerc,2)}%')
print(f'Porcentaje de personas que murieron: {round(diedPerc,2)}%')

Porcentaje de personas que sobrevivieron: 38.38%
Porcentaje de personas que murieron: 61.62%


7. Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.

In [72]:
survFirst = data.loc[(data['Pclass'] == 1) & (data['Survived'] == 1)].size
survSecond = data.loc[(data['Pclass'] == 2) & (data['Survived'] == 1)].size
survThird = data.loc[(data['Pclass'] == 3) & (data['Survived'] == 1)].size

totalFirst = data.loc[data['Pclass'] == 1].size
totalSecond = data.loc[data['Pclass'] == 2].size
totalThird = data.loc[data['Pclass'] == 3].size

survFirstPerc = (survFirst / totalFirst) * 100
survSecondPerc = (survSecond / totalSecond) * 100
survThirdPerc = (survThird / totalThird) * 100

print(f'Porcentaje de sobrevivientes en primera clase: {round(survFirstPerc,2)}%')
print(f'Porcentaje de sobrevivientes en segunda clase: {round(survSecondPerc,2)}%')
print(f'Porcentaje de sobrevivientes en tercera clase: {round(survThirdPerc,2)}%')

Porcentaje de sobrevivientes en primera clase: 62.96%
Porcentaje de sobrevivientes en segunda clase: 47.28%
Porcentaje de sobrevivientes en tercera clase: 24.24%


8. Eliminar del DataFrame los pasajeros con edad desconocida.

In [108]:
data.dropna(subset = ['Age'], inplace = True)

acum = data['Age'].isnull().sum();

if (acum == 0):
  print('Se eliminaron exitosamente todos los pasajeros con edad desconocida.')
elif (acum > 0):
  print(f'No se eliminaron todos los pasajeros con edad desconocida.')


Se eliminaron exitosamente todos los pasajeros con edad desconocida.
