<a href="https://colab.research.google.com/github/A01286211/M1-Act5-SZD/blob/main/M1_Actividad_5_Programaci%C3%B3n_en_Python_Librer%C3%ADas_Numpy_Matplotlib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M1 Act 5 Programación en Python
### Sebastián Zaragoza Díaz A01286211
### Análisis de Ciencia de Datos (Gpo 101)
### Prof. Rasikh Tariq

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Ejercicio 1 - Numpy

 1. Crear un vector “x” con 10 ceros y mostrarlo.

In [7]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Modificar el quinto elemento del vector x para que su valor sea 3.

In [8]:
x[4] = 3 # índice del vector comienza en 0
print(x)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


3. Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.

In [66]:
y = np.arange(1,21)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


4. Crear un vector “z” con valores del 1 al 20, de 2 en 2.

In [16]:
z = np.arange(1,20,2)
print(z)

[ 1  3  5  7  9 11 13 15 17 19]


5. Crear una matriz w de 3x2, con valores iniciales en 0.

In [27]:
w = np.zeros([3,2])
print(w)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


6. Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.

In [29]:
w[1,1] = 5 # De nuevo, índice comienza en 0
print(w)

[[0. 0.]
 [0. 5.]
 [0. 0.]]


7. Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.

In [61]:
vec5 = np.random.randint(1,11,5)
print(vec5)

[ 7  4  2 10  2]


8. Crear el arreglo x1 de la lista [1,2,3]

In [64]:
x1 = np.array([1,2,3])
print(x1)

[1 2 3]


9.  Sumar 10 a cada elemento del vector

In [65]:
x1 = x1 + 10
print(x1)

[11 12 13]


### Ejercicio 2 - Titanic

1. Generar un DataFrame con los datos del archivo.